import { GoogleGenAI } from "@google/genai";
import { HeadshotStyle, BackgroundOption } from "../constants";

export interface GenerationResult {
  base64: string;
  generationTime: number;
  generationId: string;
}

export async function generateHeadshot(
  imageBuffer: string, // base64
  style: HeadshotStyle,
  background?: BackgroundOption
): Promise<GenerationResult> {
  const startTime = Date.now();
  const generationId = crypto.randomUUID();
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  
  console.log("[GeminiService] Preparing prompt for style:", style.name);
  const backgroundPrompt = background 
    ? `The background should be: ${background.prompt}.` 
    : "";

  try {
    console.log("[GeminiService] Calling generateContent...");
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: imageBuffer.split(',')[1] || imageBuffer,
              mimeType: 'image/jpeg',
            },
          },
          {
            text: `Transform this casual selfie into a professional headshot. 
            Style: ${style.name}. 
            Specific style instructions: ${style.prompt}. 
            ${backgroundPrompt}
            Maintain the person's facial features accurately but enhance the lighting, background, and attire to be professional. 
            The output should be a single high-quality professional headshot.`,
          },
        ],
      },
    });

    console.log("[GeminiService] Response received from Gemini API.");
    
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        console.log("[GeminiService] Image part found in response.");
        return {
          base64: `data:image/png;base64,${part.inlineData.data}`,
          generationTime: Date.now() - startTime,
          generationId
        };
      }
    }

    console.warn("[GeminiService] No image part found in candidates.");
    throw new Error("No image generated by the AI.");
  } catch (error) {
    console.error("[GeminiService] API Error:", error);
    throw error;
  }
}
